package gov.michigan.lara.controller;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class CommitInfoController {
    @Value("${git.commit.message.short}")
    private String commitMessage;

    @Value("${git.branch}")
    private String branch;

    @Value("${git.commit.id}")
    private String commitId;

    @Value("${git.commit.id.describe-short}")
    private String describeShort;

    @Value("${git.build.time}")
    private String buildTime;

    @RequestMapping("/commitId")
    public Map<String, String> getCommitId() {
        Map<String, String> result = new HashMap<>();
        result.put("commitMessage",commitMessage);
        result.put("branch", branch);
        result.put("commitId", commitId);
        result.put("describeShort", describeShort);
        result.put("buildTime", buildTime);
        return result;
    }

    // #Generated by Git-Commit-Id-Plugin
    // #Wed Nov 01 16:13:42 EDT 2023
    // git.tags=
    // git.closest.tag.commit.count=
    // git.build.version=1.0
    // git.commit.user.name=Zach
    // git.commit.id.abbrev=50048bc
    // git.branch=master
    // git.build.host=T60844WGJYD3
    // git.commit.id.describe-short=50048bc-dirty
    // git.commit.id.describe=50048bc-dirty
    // git.build.user.email=
    // git.commit.id=50048bcd2be315d1082aab3023a2aa48c5dc1b44
    // git.commit.message.short=reworking webapp
    // git.commit.user.email=zach.johnson47@gmail.com
    // git.closest.tag.name=
    // git.commit.time=2023-11-01T14\:48\:32-0400
    // git.build.time=2023-11-01T16\:13\:42-0400
    // git.build.user.name=
    // git.dirty=true
    // git.commit.message.full=reworking webapp
    // git.remote.origin.url=https\://github.com/algebraic/workhorse.git

}
